//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsoznMain
    {
        public int ID { get; set; }
        public string Cel { get; set; }
        public string DRrazum { get; set; }
        public string Prostr { get; set; }
        public int Ocenkaemotion { get; set; }
        public string Emotion { get; set; }
        public string Do { get; set; }
        public string Think { get; set; }
        public string Time { get; set; }
    }
}
